/** The sample pack's customer and instalment references (see presentationSamples in lib/presenter-brief.ts). */
export const PRESENTATION_CUSTOMER = 'PRES-C001';
export const PRESENTATION_INSTALMENT = 'PRES-D001';

/**
 * Presenter guidance describes existing workflows; it is never operational evidence. The nine moments are the demo of a
 * 20-minute investor meeting, from 2:00 to 14:00 (meetingRunSheet in lib/presenter-brief.ts): the six collections
 * moments in their order, then connected banking, then the evidence to take away. Each is told over what Prepare for
 * presentation leaves for the active lender: the sample customers and instalments imported and the payment batch
 * checked but not imported, three daily closes with the latest waiting for Finance review, one claimed case, three
 * checkouts (confirmed, awaiting authorisation, outcome unknown), a reviewed credit assessment and a refused one,
 * Cash Desk set up with a forecast and an accounting draft and a payroll plan waiting for approval, and a saved dispute
 * pack and billing statement. `seconds` is a moment's length, which the run sheet adds up; `time` says it in words.
 */
export const presentationSteps = [
  { title: 'Start with the work', time: '1 minute', seconds: 60, href: '/overview', action: 'Open Overview', value: 'Know what needs attention before the day begins.', show: 'Name the sample lender you chose. Point out outstanding instalments, matches to review and open exceptions.', say: 'Valo Pay brings payment evidence and the work around it into one place for a lender’s Operations and Finance teams.', fallback: 'Use the figures on screen. They are sample data, not real growth or measured savings.' },
  { title: 'Bring in payment evidence', time: '90 seconds', seconds: 90, href: '/imports', action: 'Open Import batches', value: 'Check records before they affect the books.', show: 'Prepare for presentation imported the sample customers and instalments. Open the prepared payment batch, which is checked but not imported. Show the naira amount and the row checks, then select Import checked batch once.', say: 'A file is checked and saved with its source. An error can be corrected before the batch is imported.', fallback: 'If the file is already imported, show its saved result and where it came from. Do not change its source row IDs just to import it again. If there is no payment batch, import the sample payment file from the Presentation page by hand.' },
  // The sample payment names its instalment and equals it, so rule R1 matches it automatically and with certainty: it is never
  // in Matches to review. Its match and explanation are in the sample customer's history, which the guide opens once imported.
  { title: 'Explain the match', time: '90 seconds', seconds: 90, href: `/customers?q=${PRESENTATION_CUSTOMER}`, customer: PRESENTATION_CUSTOMER, action: 'Open the sample customer', value: 'Connect a payment to the instalment it pays.', show: `After importing the payment file, run reconciliation on the Reconciliation page, if your role allows it. Then open the sample customer ${PRESENTATION_CUSTOMER} and its history. The payment names instalment ${PRESENTATION_INSTALMENT} and the amounts are equal, so rule R1 matched them automatically, with the confidence Certain. The history shows the match with its rule and explanation. It never appears in Matches to review, which holds only matches Finance must confirm.`, say: 'When a payment names the instalment it pays and the amounts agree, the match is made automatically and recorded with its reason. A less certain match waits for Finance to confirm it instead of being accepted silently.', fallback: 'If the customer is not found, this lender is not prepared yet. Select Prepare for presentation on the Presentation page. If the payment is still unallocated, reconciliation has not run since the import. Run it. To show a match that waits for Finance, open Matches to review in Reconciliation. Say that it comes from the ready-made sample data, not from your file. If access is refused, explain which role is needed. Do not change permissions for the presentation.' },
  { title: 'Give an exception an owner', time: '75 seconds', seconds: 75, href: '/exceptions', action: 'Open Exceptions', value: 'Turn an unresolved exception into work someone owns.', show: 'Open the case of the exception that shows Assigned to. Its handover history shows who claimed it, the next step and the handover note. Then choose another open exception and show its owner and when it is due.', say: 'When something needs investigating, the next person can see the context, the next step and the handover history.', fallback: 'If no exceptions are open, show a resolved case. Resolving an exception does not make a payment or supply missing evidence.' },
  { title: 'Review the day’s close', time: '75 seconds', seconds: 75, href: '/reports#daily-closes', action: 'Open Reports', value: 'Show the difference between a recorded daily close and one a different person has reviewed.', show: 'Daily close records holds a close for each of the 3 previous business days. Open the latest and the sources it covers. Then find it in Close review, where it waits for a different Finance reviewer.', say: 'A daily close saves the evidence available at that time. Missing sources stay visible. A different person must review it, so no one approves their own close.', fallback: 'A missing source or a review still waiting is a useful safeguard to explain. Never describe it as complete. After the live import, Close review says the records changed after this close: a close can be approved only while it still matches its records. Switching demo roles is not a second person.' },
  { title: 'Take a payment by bank', time: '90 seconds', seconds: 90, href: '/pay-by-bank', action: 'Open Pay by Bank', value: 'Let a customer pay one instalment from their own bank.', show: 'Checkout history holds 3 prepared checkouts. Select each one: Confirmed, Awaiting authorisation and Outcome unknown. Its progress shows which bank steps it has passed.', say: 'The customer authorises each payment at their own bank. Only a payment the bank or provider confirms counts. An unknown outcome holds the instalment until it is known.', fallback: 'A customer has 15 minutes to authorise a checkout, so the waiting one may show Checkout expired. An expired checkout does not mean that a payment failed. Live payments and bank connections are switched off. No money moved. Nothing was sent to a bank.' },
  { title: 'Check an applicant’s affordability', time: '90 seconds', seconds: 90, href: '/credit-desk', action: 'Open Credit Desk', value: 'See whether an applicant can afford the repayments, and why.', show: 'Open the prepared assessment. Show the score, the affordability check and, in Review history, the review another demo role recorded. Then, in Assessment version, choose the applicant who refused permission. There is no score, and the refusal does not count against them.', say: 'With the applicant’s permission, Credit Desk reads their bank transactions and checks whether they can afford the repayments. A different person reviews each assessment. A credit result is not a lending decision.', fallback: 'The score uses sample rules that have not been validated for real lending. Say so if asked. Switching demo roles is not a second person: in live use, a different team member reviews each assessment.' },
  { title: 'See the business’s cash', time: '75 seconds', seconds: 75, href: '/cash-desk', action: 'Open Cash Desk', value: 'Help a small business plan its cash and prepare its accounting and payroll.', show: 'Cash and forecast shows the sample business’s balances and its saved 30-day forecast. Then open Accounting and Payroll funding. The accounting draft and the payroll funding plan each wait for a different Finance reviewer to approve them.', say: 'Cash Desk shows a small business its cash for the next 30 days and prepares its accounting and payroll work for review. Nothing was posted to accounting software. No VAT return was filed and no tax was paid. No one has been paid.', fallback: 'A forecast is a planning estimate, not money held or set aside. If a balance is out of date, say so: each one shows its sample bank timestamp. Permission to read an account is not permission to take money from it.' },
  { title: 'Leave with the evidence', time: '60 seconds', seconds: 60, href: '/exports', action: 'Open Saved exports', value: 'Let people check the work after the meeting.', show: 'Open the prepared dispute pack for Ada Okonkwo. Show its status and download the ready file. The billing statement is saved there too. To start a new dispute pack, use a customer’s history.', say: 'Evidence can be downloaded after the session. Its status shows whether the file is ready or needs attention.', fallback: 'If an export is still being prepared, show its real status and use the sample file you downloaded earlier. Do not call a waiting file ready.' },
] as const;

export const presentationChecks = [
  { id: 'build', label: 'I opened the right version of Valo Pay in a new private window.' },
  { id: 'lender', label: 'I chose one sample lender and checked what my role allows.' },
  { id: 'prepare', label: 'I pressed Prepare for presentation for this lender and checked each page I will show.' },
  { id: 'records', label: 'I left the prepared payment batch unimported, to import it once during the demo.' },
  { id: 'close', label: 'I checked which sources the daily close covers and its review status.' },
  { id: 'backup', label: 'I downloaded a sample export and prepared a backup recording or screenshots.' },
  { id: 'claims', label: 'I will say which figures are sample data and what is still needed for live use.' },
] as const;
