/** The sample pack's customer and instalment references (see presentationSamples in lib/presenter-brief.ts). */
export const PRESENTATION_CUSTOMER = 'PRES-C001';
export const PRESENTATION_INSTALMENT = 'PRES-D001';

/** Presenter guidance describes existing workflows; it is never operational evidence. */
export const presentationSteps = [
  { title: 'Start with the work', time: '45 seconds', href: '/overview', action: 'Open Overview', value: 'Know what needs attention before the day begins.', show: 'Name the sample lender you chose. Point out outstanding instalments, matches to review and open exceptions.', say: 'Valo Pay brings payment evidence and the work around it into one place for a lender’s Operations and Finance teams.', fallback: 'Use the figures on screen. They are sample data, not real growth or measured savings.' },
  { title: 'Bring in payment evidence', time: '1 minute', href: '/imports', action: 'Open Import batches', value: 'Check records before they affect the books.', show: 'Open the prepared payment batch. Show the naira amount and the row checks, then import it once.', say: 'A file is checked and saved with its source. An error can be corrected before the batch is imported.', fallback: 'If the file is already imported, show its saved result and where it came from. Do not change its source row IDs just to import it again.' },
  // The sample payment names its instalment and equals it, so rule R1 matches it automatically and with certainty: it is never
  // in Matches to review. Its match and explanation are in the sample customer's history, which the guide opens once imported.
  { title: 'Explain the match', time: '90 seconds', href: `/customers?q=${PRESENTATION_CUSTOMER}`, customer: PRESENTATION_CUSTOMER, action: 'Open the sample customer', value: 'Connect a payment to the instalment it pays.', show: `After importing the payment file, run reconciliation on the Reconciliation page, if your role allows it. Then open the sample customer ${PRESENTATION_CUSTOMER} and its history. The payment names instalment ${PRESENTATION_INSTALMENT} and the amounts are equal, so rule R1 matched them automatically, with the confidence Certain. The history shows the match with its rule and explanation. It never appears in Matches to review, which holds only matches Finance must confirm.`, say: 'When a payment names the instalment it pays and the amounts agree, the match is made automatically and recorded with its reason. A less certain match waits for Finance to confirm it instead of being accepted silently.', fallback: 'If the customer is not found, the sample files are not imported for this lender yet. Import them first. If the payment is still unallocated, reconciliation has not run since the import. Run it. To show a match that waits for Finance, open Matches to review in Reconciliation. Say that it comes from the ready-made sample data, not from your file. If access is refused, explain which role is needed. Do not change permissions for the presentation.' },
  { title: 'Give an exception an owner', time: '1 minute', href: '/exceptions', action: 'Open Exceptions', value: 'Turn an unresolved exception into work someone owns.', show: 'Choose another open sample exception. Show the customer, the owner and the deadline, then open its case.', say: 'When something needs investigating, the next person can see the context, the next step and the handover history.', fallback: 'If no exceptions are open, show a resolved case. Resolving an exception does not make a payment or supply missing evidence.' },
  { title: 'Review the day’s close', time: '1 minute', href: '/reports#daily-closes', action: 'Open Reports', value: 'Show the difference between a recorded daily close and one a different person has reviewed.', show: 'Open a daily close you rehearsed and the sources it covers. Use Close review to show what Finance approved, or where it requested changes.', say: 'A daily close saves the evidence available at that time. Missing sources stay visible, and the review is a separate decision.', fallback: 'A missing source or a review still waiting is a useful safeguard to explain. Never describe it as complete. Switching demo roles is not a second person.' },
  { title: 'Leave with the evidence', time: '45 seconds', href: '/exports', action: 'Open Saved exports', value: 'Let people check the work after the meeting.', show: 'Open a saved export for this lender. Show its status and download the ready file. To start a new dispute pack, use a customer’s history.', say: 'Evidence can be downloaded after the session. Its status shows whether the file is ready or needs attention.', fallback: 'If an export is still being prepared, show its real status and use the sample file you downloaded earlier. Do not call a waiting file ready.' },
] as const;

export const presentationChecks = [
  { id: 'build', label: 'I opened the right version of Valo Pay and checked the pages I will show.' },
  { id: 'lender', label: 'I chose one sample lender and checked what my role allows.' },
  { id: 'records', label: 'I rehearsed the import, match and case I will use.' },
  { id: 'close', label: 'I checked which sources the daily close covers and its review status.' },
  { id: 'backup', label: 'I downloaded a sample export and prepared a backup recording or screenshots.' },
  { id: 'claims', label: 'I will say which figures are sample data and what is still needed for live use.' },
] as const;
