import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, Check, Download, FileText, Play } from 'lucide-react';
import { useWorkspace } from '@/lib/workspace-context';
import { usePresentation, usePresentationHref } from '@/components/presentation-guide';
import { presentationChecks, presentationSteps } from '@/lib/presentation';
import { presentationSamples, presenterBrief, downloadPresentationFile, sampleImportSteps } from '@/lib/presenter-brief';
import { formatDate } from '@/lib/formatters';
import { Button } from '@/components/ui/button';
import { PresentationPreparation } from '@/components/presentation-preparation';

export default function PresentationPage() {
  const { state, save } = usePresentation();
  const { workspace, merchantId } = useWorkspace();
  const [date] = useState(() => new Date(Date.now() + 3_600_000).toISOString().slice(0, 10));
  const [notice, setNotice] = useState('');
  const lender = workspace?.merchants.find(m => m.id === merchantId);
  const hrefFor = usePresentationHref(true);
  const canStart = Boolean(merchantId) && workspace?.environment === 'sandbox';
  function download(filename: string, content: string, csv = false) {
    try { downloadPresentationFile(filename, content, csv); setNotice(`Download requested: ${filename}. Check your browser’s downloads.`); }
    catch { setNotice('Download not started. Try again. If it keeps failing, try another browser.'); }
  }
  return <div className="space-y-8 pb-8">
    <section className="relative overflow-hidden rounded-2xl border bg-card p-6 sm:p-8">
      <div className="grid gap-7 lg:grid-cols-[1.5fr_1fr]">
        <div><h1 className="max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Presentation</h1><p className="mt-3 max-w-xl text-base font-medium">Show investors how a lender gets from records to a reviewed close, and what connected banking adds: a demo of about 12 minutes in a 20-minute meeting.</p><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">One lender’s working day: check the evidence, explain the match, give an exception an owner and review the close. Then take a payment by bank, check an applicant’s affordability and see a small business’s cash.</p>
          <div className="mt-6 flex flex-wrap gap-3"><Button disabled={!canStart} onClick={() => save({ ...state, active: true, step: 0 })}><Play className="mr-2 h-4 w-4" aria-hidden="true" />Start presentation guide</Button><Button variant="outline" onClick={() => download('valo-pay-presenter-brief.md', presenterBrief(date))}><Download className="mr-2 h-4 w-4" aria-hidden="true" />Download presenter brief</Button></div>
          {!canStart && <p className="mt-3 text-xs leading-5 text-muted-foreground">{merchantId ? 'The presentation guide works only in the sandbox.' : 'Choose a lender in Active lender to start the guide.'}</p>}
          <p className="mt-3 text-xs leading-5 text-muted-foreground">Starting the guide only adds page links and talking points. Every page keeps its usual checks and permissions.</p>
          <p className="mt-3 text-xs leading-5 text-muted-foreground">The presenter brief holds the 20-minute run sheet and short answers to likely questions.</p>
        </div>
        <section className="rounded-xl border bg-secondary/25 p-5"><p className="text-xs font-semibold text-muted-foreground">Active lender</p><p className="mt-3 text-xl font-semibold">{lender?.name || 'None chosen'}</p><p className="mt-2 text-sm">{workspace?.accessMode === 'staff' ? 'Role' : 'Demo role'}: {workspace?.role || 'None'}</p><p className="mt-4 border-t pt-4 text-sm leading-6 text-muted-foreground">Sample data only. No money moves. The figures on screen show how the work is done. They are not real results, such as growth, better recoveries or live payments.</p><Link href="/pilot" className="mt-3 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-primary underline underline-offset-4">Open Pilot journey<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></section>
      </div>
    </section>
    <PresentationPreparation />

    <section aria-labelledby="demo-story"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold text-primary">The product story</p><h2 id="demo-story" className="mt-2 text-2xl font-semibold tracking-tight">Nine moments that explain the value</h2></div><p className="text-sm text-muted-foreground">Open each page when you are ready.</p></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{presentationSteps.map((step, index) => <article key={step.href} className="flex flex-col rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-sm font-semibold text-primary">{String(index + 1).padStart(2, '0')}</span><span className="text-xs text-muted-foreground">{step.time}</span></div><h3 className="mt-4 font-semibold">{step.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">{step.value}</p><Link href={hrefFor(step)} className="mt-4 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-primary underline underline-offset-4" onClick={() => save({ ...state, step: index })}>{step.action}<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></article>)}</div>
    </section>

    <div className="grid items-start gap-6 lg:grid-cols-2">
      <section aria-labelledby="demo-checks" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-checks" className="text-lg font-semibold">Before you share your screen</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Start with Prepare for presentation, then check each page yourself. This checklist is for you, for this session and lender. Ticking an item does not test Valo Pay, complete a task or approve a pilot.</p><p aria-live="polite" className="mt-3 text-sm font-medium">{state.checked.length} of {presentationChecks.length} preparation checks marked</p><div className="mt-3 divide-y">{presentationChecks.map(check => <label key={check.id} className="flex cursor-pointer items-start gap-3 py-3 text-sm leading-6"><input type="checkbox" className="mt-1 h-4 w-4 shrink-0 accent-primary" checked={state.checked.includes(check.id)} onChange={e => save({ ...state, checked: e.target.checked ? [...state.checked, check.id] : state.checked.filter(id => id !== check.id) })} /><span>{check.label}</span></label>)}</div><Button size="sm" variant="ghost" onClick={() => save({ ...state, checked: [] })}>Clear preparation checks</Button><p className="mt-1 text-xs text-muted-foreground">This clears only the checkboxes. Your records stay as they are.</p></section>
      <section aria-labelledby="demo-pack" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-pack" className="text-lg font-semibold">Sample files</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Prepare for presentation imports the customer and instalment files for this lender. It also saves and checks the payment file, so you can import it once during the demo. Download the files only to import them by hand. Each amount is <strong className="text-foreground">₦18,000.50</strong>. The files’ business date is {formatDate(date)} (WAT).</p><ol className="mt-4 space-y-3">{presentationSamples(date).map((sample, index) => <li key={sample.filename} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><span className="flex items-center gap-2 text-sm"><FileText className="h-4 w-4 text-muted-foreground" aria-hidden="true" />{index + 1}. {sample.kind}</span><Button size="sm" variant="outline" onClick={() => download(sample.filename, sample.csv, true)}><Download className="mr-2 h-4 w-4" aria-hidden="true" /><span>Download CSV <span className="sr-only">of {sample.kind.toLowerCase()}</span></span></Button></li>)}</ol><details className="mt-4 text-sm"><summary className="min-h-10 cursor-pointer py-2 font-medium">Import instructions and repeat rehearsals</summary><p className="mt-2 leading-6">{sampleImportSteps} Set the business date to {formatDate(date)}. Select Save and check batch, check the preview, then select Import checked batch once. Then select Run reconciliation on the Reconciliation page.</p><p className="mt-3 leading-6 text-muted-foreground">Prepare for presentation imports the same files, so import them by hand only in a sandbox where you have not selected it. Files you import again keep their source row IDs, so they may be reported as duplicates. For a fresh run, use a private browser window or a new, empty sample lender. A new lender has no sample exceptions until you prepare some. Never clear an existing workspace.</p></details></section>
    </div>

    <section aria-labelledby="demo-boundaries" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-boundaries" className="text-lg font-semibold">Keep the claims as clear as the product</h2><div className="mt-4 grid gap-6 md:grid-cols-3"><div><h3 className="flex items-center gap-2 text-sm font-semibold"><Check className="h-4 w-4 text-primary" aria-hidden="true" />Demonstrate in the sandbox</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Saved imports, match explanations, assigned cases, daily closes, sample checkouts, credit assessments, Cash Desk forecasts and drafts, and saved exports. Show each record’s real status.</p></div><div><h3 className="text-sm font-semibold">Explain what still needs checking</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Live Paystack and bank connections, team member sign-in with two-step verification, managed keys, restricted database access, recovery, and final acceptance where Valo Pay will run.</p></div><div><h3 className="text-sm font-semibold">Bring separate proof for business claims</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Conversations with lenders, signed agreements and measured pilot results, where you have them. Sample totals and a completed checklist do not prove any of these.</p></div></div></section>
    <p role="status" className="text-sm text-muted-foreground">{notice}</p>
  </div>;
}
