#!/usr/bin/env bash
# Rebuild artifacts/api-server/src/fonts/valo-pack-sans.ts from the installed
# Liberation Sans (see the README beside it). Needs Python 3 with fontTools
# (pip install fonttools). Run from the repository root.
set -euo pipefail
python3 - <<'PY'
import base64, subprocess, sys, tempfile, textwrap
from pathlib import Path
from fontTools.ttLib import TTFont

SOURCE = Path("/usr/share/fonts/truetype/liberation")
TARGET = Path("artifacts/api-server/src/fonts/valo-pack-sans.ts")
# Latin script with its marks, plus the punctuation, currency and symbols the packs print.
UNICODES = "U+0000-007F,U+00A0-024F,U+0259,U+02BB-02BC,U+02C6-02DC,U+0300-036F,U+1E00-1EFF,U+2000-206F,U+20A0-20CF,U+2122,U+2190-2199,U+2212,U+2260-2265,U+25A0-25CF,U+2713-2714"
FAMILY = "Valo Pack Sans"

blocks = {}
with tempfile.TemporaryDirectory() as work:
    for weight in ("Regular", "Bold"):
        subset = Path(work) / f"ValoPackSans-{weight}.ttf"
        subprocess.run([sys.executable, "-m", "fontTools.subset", str(SOURCE / f"LiberationSans-{weight}.ttf"), f"--unicodes={UNICODES}",
                        "--layout-features=*", "--name-IDs=*", "--notdef-outline", f"--output-file={subset}"], check=True)
        font = TTFont(subset)
        postscript = f"ValoPackSans-{weight}"
        for record in font["name"].names:
            if record.nameID in (1, 16): record.string = FAMILY
            elif record.nameID in (2, 17): record.string = weight
            elif record.nameID == 3: record.string = f"ValoPay1;{postscript};2.1.5-subset"
            elif record.nameID == 4: record.string = f"{FAMILY} {weight}"
            elif record.nameID == 6: record.string = postscript
            elif record.nameID == 10: record.string = "A Latin subset of Liberation Sans 2.1.5, renamed as the SIL Open Font License's Reserved Font Name clause requires. Embedded in Valo Pay 1's PDF exports."
        font.save(subset)
        data = subset.read_bytes()
        blocks[weight] = ("\n".join(textwrap.wrap(base64.b64encode(data).decode(), 120)), len(data), len(font.getGlyphOrder()))
        print(weight, len(font.getGlyphOrder()), "glyphs,", len(data), "bytes")

TARGET.write_text(f'''/**
 * Valo Pack Sans, the typeface embedded in the PDF exports: a Latin subset of
 * Liberation Sans 2.1.5 (SIL Open Font License 1.1, LICENSE.md and README.md
 * beside this file), as base64 so it travels as source text and needs no file
 * access at run time. Generated by scripts/subset-pack-fonts.sh; do not edit.
 */

/** Regular weight, {blocks["Regular"][1]:,} bytes of TrueType. */
export const VALO_PACK_SANS_REGULAR = `
{blocks["Regular"][0]}
`;

/** Bold weight, {blocks["Bold"][1]:,} bytes of TrueType. */
export const VALO_PACK_SANS_BOLD = `
{blocks["Bold"][0]}
`;
''')
print("wrote", TARGET)
PY
