import { Link } from "wouter";
import { hasFeeSchedule } from "@workspace/valo-pay-1-schema";
import { useWorkspace } from "@/lib/workspace-context";
import { formatCount, formatDate, formatKobo, formatNumber } from "@/lib/formatters";
import { formatMinor, formatWithOtherCurrencies } from "@/lib/currencies";
import { recordPage } from "@/lib/record-navigation";
import { readableLabel } from "@/components/record-label";

const count = (value: unknown) => value === undefined || value === null ? "Not recorded" : formatNumber(Number(value));
/** A matching rule by its name ("Rule R1"); any other key, such as a manual allocation, through the shared labels. */
const ruleName = (rule: string) => /^R\d+$/.test(rule) ? `Rule ${rule}` : readableLabel(rule);
const money = (value: any) => value ? `${value.count === undefined ? "Count not recorded" : formatCount(Number(value.count), "item")} · ${formatWithOtherCurrencies(Number(value.kobo || 0), value.otherCurrencies, "item")}` : "Not recorded";
const engineLabels: Record<string, string> = { observationsResolved: "Payment evidence resolved", canonicalPayments: "New payments recorded", settlementStatementsMatched: "Settlement statements matched", settlementVariances: "Settlement differences", paymentStatusesRepaired: "Payment statuses corrected", dueStatusesRepaired: "Instalment statuses corrected", paymentsSkipped: "Payments skipped", attemptOutcomesConfirmed: "Collection outcomes confirmed", proposed: "Matches to review", unallocated: "Unallocated payments", possibleDuplicates: "Possible duplicates", agedUnallocated: "Unallocated for more than 24 hours", finalAttemptExceptions: "Exceptions after the final attempt", disputesFrozen: "Instalments paused for disputes", noticesNotEvidenced: "Missing notice evidence", retryDecisionsRecorded: "Retry decisions recorded", unknownOutcomes: "Collection outcomes unknown", checkoutOutcomesUnknown: "Checkout outcomes unknown", exceptionsOpened: "Exceptions opened", exceptionsCleared: "Exceptions closed", exceptionCurrenciesRecorded: "Currencies added to exceptions", settlementProviderIdentityHolds: "Batches on hold: connection not confirmed", settlementProviderIdentityReleases: "Batch holds released", settlementProviderIdentityReviews: "Batch hold reviews applied", legacyReversalReviewsPending: "Earlier reversal decisions needing review", legacyReversalStatusesRestored: "Instalment statuses restored after reversal review", settlementLinesSeparated: "Settlement lines separated" };

function Figures({ rows }: { rows: Array<[string, string]> }) {
  return <dl className="grid gap-x-6 gap-y-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value}</dd></div>)}</dl>;
}

/** A statement of frozen close evidence. Links open today's records; they never replace the recorded amounts. */
export function CloseStatement({ close }: { close: any }) {
  const { merchantId } = useWorkspace(), report = close.data.report;
  const link = (kind: string, id: string, label: string, reference?: string) => { const href = reference && ["settlement-batches", "payments", "observations"].includes(kind) ? `/reconciliation?${new URLSearchParams({ q: reference, lender: merchantId || "" })}` : recordPage(kind, id, merchantId || ""); return href ? <Link href={href} className="text-primary underline">{label}</Link> : label; };
  if (!report) return <p className="text-sm text-muted-foreground">A detailed report was not recorded for this close. Its saved review and decision remain available below.</p>;
  return <section aria-label="Recorded close statement" className="space-y-5">
    <div className="rounded-lg bg-secondary/20 p-4"><h3 className="font-semibold">Recorded close statement</h3><p className="mt-1 text-sm text-muted-foreground">{report.period?.from ? `${formatDate(report.period.from)} to ` : "From the start of the records to "}{formatDate(report.period?.to || close.createdAt)}. These figures are the saved evidence for this close. Supporting links open the current records.</p></div>
    <section className="space-y-3"><h4 className="text-sm font-semibold">Payments and matching</h4><Figures rows={[["Unallocated at start", money(report.openingUnallocated)], ["Payment evidence received", count(report.observations?.received)], ["Payments linked to evidence", count(report.observations?.paymentsResolvedTo)], ["New payments recorded", count(report.observations?.canonicalPaymentsCreated)], ["Confirmed allocations", money(report.allocated)], ["Matches to review", money(report.proposed)], ["Unallocated at close", money(report.unallocated)], ["Unallocated for more than 24 hours", count(report.unallocated?.olderThan24Hours)], ["Possible duplicate payments", money(report.possibleDuplicates)]]} /><Link href="/reconciliation" className="inline-flex min-h-9 items-center text-sm text-primary underline">Open Reconciliation</Link></section>
    {!!Object.keys(report.observations?.bySource || {}).length && <section className="space-y-3"><h4 className="text-sm font-semibold">Payment evidence by source</h4>{Object.entries(report.observations.bySource).map(([source, value]: [string, any]) => <div key={source} className="rounded-lg border p-3"><p className="mb-2 text-sm font-medium">{readableLabel(source)}</p><Figures rows={[["Received", count(value.received)], ["Resolved", count(value.resolved)], ["Unresolved", count(value.unresolved)], ["Payments linked", count(value.paymentsResolvedTo)], ["Settlement batches linked", count(value.batchesResolvedTo)]]} /></div>)}</section>}
    {!!Object.keys(report.allocatedByRule || {}).length && <section className="space-y-3"><h4 className="text-sm font-semibold">Confirmed allocations by rule</h4>{Object.entries(report.allocatedByRule).map(([rule, value]: [string, any]) => <div key={rule} className="rounded-lg border p-3"><p className="mb-2 text-sm font-medium">{ruleName(rule)}</p><Figures rows={[["Allocations", count(value.count)], ["Value (₦)", formatKobo(value.kobo)], ["Automatic allocations", count(value.automatic)]]} /></div>)}</section>}
    <section className="space-y-3"><h4 className="text-sm font-semibold">Settlement differences</h4><Figures rows={[["Batches needing review", count(report.variances?.count)], ["Fee difference (₦)", report.variances?.feeVarianceKobo === undefined ? "Not recorded" : formatKobo(report.variances.feeVarianceKobo)]]} />{(report.variances?.batches || []).map((batch: any) => <div key={batch.batchId} className="rounded-lg border border-warning-border p-3 text-sm"><p className="mb-2 font-medium">{link("settlement-batches", batch.batchId, batch.reference || batch.batchId, batch.reference)}</p><Figures rows={[["After fees (provider)", formatMinor(batch.netKobo, batch.currency || "NGN")], ["After fees (bank statement)", batch.statementNetKobo == null ? "Not recorded" : formatMinor(batch.statementNetKobo, batch.currency || "NGN")], ["Fee difference", hasFeeSchedule(batch.currency || "NGN") ? formatMinor(batch.feeVarianceKobo, batch.currency || "NGN") : `Not checked: no ${batch.currency} fee schedule`]]} /><p className="mt-2 whitespace-pre-wrap text-muted-foreground">{batch.explanation || "No explanation recorded."}</p></div>)}</section>
    <section className="space-y-3"><h4 className="text-sm font-semibold">Exceptions and retry decisions</h4><Figures rows={[["Exceptions opened", count(report.exceptions?.opened?.count)], ["Exceptions closed", count(report.exceptions?.closed?.count)], ["Open at close", count(report.exceptions?.openAtClose)], ["Overdue at close", count(report.exceptions?.overdueAtClose)], ["Retry decisions recorded", count(report.retryDecisions?.recorded)], ["Final attempts", count(report.retryDecisions?.finalAttempts)], ["Instalments paused for disputes", count(report.retryDecisions?.disputesFrozen)], ["Deferred for missing notice evidence", count(report.retryDecisions?.noticesNotEvidenced)]]} />{["opened", "closed"].map(action => Object.keys(report.exceptions?.[action]?.byType || {}).length > 0 && <p key={action} className="text-sm text-muted-foreground">{action === "opened" ? "Opened" : "Closed"} by type: {Object.entries(report.exceptions[action].byType).map(([kind, value]) => `${readableLabel(kind)}: ${count(value)}`).join("; ")}</p>)}<Link href="/exceptions" className="inline-flex min-h-9 items-center text-sm text-primary underline">Open Exceptions</Link></section>
    <section className="space-y-3"><h4 className="text-sm font-semibold">Customer balance checks</h4><Figures rows={[["Customers checked", count(report.positionRebuild?.customersChecked)], ["Instalments checked", count(report.positionRebuild?.dueItemsChecked)], ["Differences found", count(report.positionRebuild?.mismatches?.length)], ["Customer balances changed", count(report.customerPositionsChanged?.length)]]} />{(report.positionRebuild?.mismatches || []).map((item: any) => <div key={item.dueItemId} className="rounded-lg border border-warning-border p-3 text-sm"><p className="mb-2 font-medium">{link("due-items", item.dueItemId, item.reference || item.dueItemId)}</p><Figures rows={[["Outstanding as stored", formatKobo(item.storedOutstandingKobo)], ["Outstanding as recalculated", formatKobo(item.rebuiltOutstandingKobo)]]} /></div>)}{(report.customerPositionsChanged || []).map((item: any) => <details key={item.customerId} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">{item.customerName || item.customerId} · balance changed</summary><div className="mt-3 space-y-3 text-sm">{link("customers", item.customerId, "Open Customer history")}<Figures rows={["obligationsKobo", "allocatedKobo", "outstandingKobo", "unallocatedKobo"].map(key => [({ obligationsKobo: "Total owed", allocatedKobo: "Allocated", outstandingKobo: "Outstanding", unallocatedKobo: "Unallocated payments" } as Record<string, string>)[key]!, `Before: ${item.before ? formatKobo(item.before[key]) : "Not recorded"} · After: ${formatKobo(item.after[key])}`])} /></div></details>)}</section>
    {!!close.data.reviewBasis?.unresolved?.length && <section className="space-y-3"><h4 className="text-sm font-semibold">Unresolved records at close</h4>{close.data.reviewBasis.unresolved.map((item: any) => <div key={item.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{link(item.kind, item.id, item.name || item.reference || item.id, item.reference)}</p><p className="mt-1 text-muted-foreground">{[readableLabel(item.status), item.reference, formatMinor(item.amountKobo, item.currency || "NGN")].filter(Boolean).join(" · ")}</p></div>)}</section>}
    {!!report.alerts?.length && <section className="space-y-3"><h4 className="text-sm font-semibold">Alerts recorded at close</h4>{report.alerts.map((alert: any) => <div key={alert.key} className="rounded-lg border p-3 text-sm"><p className="font-medium">{alert.title} · {readableLabel(alert.severity)}</p><p className="mt-1 text-muted-foreground">{alert.detail}</p></div>)}</section>}
    {!!report.reconciliation && <details className="rounded-lg border p-3"><summary className="min-h-8 cursor-pointer text-sm font-medium">Reconciliation checks and repairs</summary><div className="mt-3 space-y-3"><Figures rows={Object.entries(engineLabels).filter(([key]) => report.reconciliation[key] !== undefined).map(([key, label]) => [label, count(report.reconciliation[key])])} />{["observationsBySource", "allocationsByRule"].map(key => Object.keys(report.reconciliation[key] || {}).length > 0 && <p key={key} className="text-sm">{key === "observationsBySource" ? "Payment evidence resolved by source" : "New allocations by rule"}: {Object.entries(report.reconciliation[key]).map(([label, value]) => `${key === "observationsBySource" ? readableLabel(label) : ruleName(label)}: ${count(value)}`).join("; ")}</p>)}{report.reconciliation.auditNote && <p className="whitespace-pre-wrap text-sm">{report.reconciliation.auditNote}</p>}</div></details>}
    <details className="rounded-lg border p-3"><summary className="min-h-8 cursor-pointer text-sm font-medium">Technical details (JSON)</summary><p className="mt-2 text-xs text-muted-foreground">The full saved report, kept for investigation.</p><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(report, null, 2)}</pre></details>
  </section>;
}
